### ISSUE TITLE
Not working in built in render pipeline 

### ISSUE THREAD

**Issue by hackeranmol** [naelstrof/UnityPenetrationTech#12]
There are no demos for built in render pipeline

So i updated all the materials manually to use built in render pipeline and also changed the penetrator shader to built in render pipeline ones 

But the dick is huge , not in its place and everything is broken after I did this ?

**Comment by naelstrof** [comment]
Dick is huge usually because Unity Penetration Tech outputs absolute vertex offsets rather than local offsets.

There's a toggle in amplify for that in the shader settings.

The system should work fine with the built-in pipeline, as it's all just generic spline maths. No matter the pipeline, you'll need to make your own shaders.

**Comment by hackeranmol** [comment]
I setup @Raliv RDP but the dick is always transparent don't know why. I don't get any response from the developer.

Do you know how to fix it ?

If not nevermind. I am using your asset but I am finding it a little hard to get started since there are no tutorials. I am glad you are here to provide support. I will experiment with myself first and then ask for help again if I got stuck since your asset seems a little complicated.

**Comment by naelstrof** [comment]
Yeah sorry, it really is complicated. Feel free to poke me with questions. I didn't really build this addon to be friendly, it just solves a very specific problem for me.
