### ISSUE TITLE
Clip range listener doesn't work in HDRP Shader Graph

### ISSUE THREAD

**Issue by bonzomi** [naelstrof/UnityPenetrationTech#3]
Platform: Unity 2021.3.4f1 LTS on HDRP 12.1.7
Using PenetrationTech [v3.0.5](https://github.com/naelstrof/UnityPenetrationTech/tree/v3.0.5)

Current output:
![image](https://user-images.githubusercontent.com/67600109/173724583-e3f80a76-f078-4d22-a224-6ef3c2c1ee9b.png)
Expected output (Using ASE version):
![image](https://user-images.githubusercontent.com/67600109/173724625-c7103357-1417-4e85-b1e9-32fe4d0f288c.png)

Using ASE also introduces weird artifacting as shown below
![image](https://user-images.githubusercontent.com/67600109/173724820-185a6a39-1069-4e50-99f8-f4a524273891.png)

On latest UnityPenetrationTech package, ASE version enlarges the penetrators and is inaccurate to actual geo. Problem persists with ShaderGraph version.

**Comment by naelstrof** [comment]
> Clip range listener doesn't work in HDRP Shader Graph

Unfortunately Shader Graph doesn't support piping data from vert to frag (You can find out more here: https://forum.unity.com/threads/compute-value-at-vert-instead-of-frag.853015/)

Since the clipping is in un-distorted world-space, it needs to do a spline distance lookup to undistort the distance-- which as things are would need to happen per-pixel. I didn't want to accidentally make something highly unoptimized, so I just simply left it out completely!

> On latest UnityPenetrationTech package, ASE version enlarges the penetrators and is inaccurate to actual geo. Problem persists with ShaderGraph version.

Make sure your Vertex Output mode is set to _Absolute_ rather than _Relative_. This can lead to the model looking twice as big, and make clipping happen at the wrong points. It might also cause weird artifacting. Hopefully that's the only problem!

**Comment by naelstrof** [comment]
I also recommend upgrading to [v3.3.2](https://github.com/naelstrof/UnityPenetrationTech/tree/v3.3.2), large amounts of bugs and functionality was needed to get it working in my game the way I wanted.

**Comment by bonzomi** [comment]
![image](https://user-images.githubusercontent.com/67600109/173769487-7f47ac95-764e-4803-b7cc-4ee56cd0360c.png)
Thanks, the vertex fix helped! I've had no problems with different models but this particular one ended up with this rendering error on the game view, looks fine in scene view. I've tried swapping materials and it didn't work.

**Comment by bonzomi** [comment]
![image](https://user-images.githubusercontent.com/67600109/173795054-5f2c53b8-2ed6-460b-b58d-19f6bb9ea32b.png)
Closing this issue, I just had to set the surface type to transparent
